### ISSUE TITLE
Create template functions

### ISSUE THREAD

**Issue by MOshima-PIFSC** [nmfs-ost/ss3diags#2]
Create @template for plotting parameters (ylim, main.title, pheight, etc.) so they are not specified in function every time. See r4ss man-oxygen for examples.

**Comment by efletcherPIFSC** [comment]
@MOshima-PIFSC Where in r4ss/r4ss is man-oxygen?

**Comment by MOshima-PIFSC** [comment]
@efletcherPIFSC  I meant [man-roxygen](https://github.com/PIFSCstockassessments/r4ss/tree/main/man-roxygen)

**Comment by efletcherPIFSC** [comment]
@MOshima-PIFSC  I can take a look at this after the break.

**Comment by efletcherPIFSC** [comment]
May reconsider  `@inheritParams` as an alternative to `@template`
r4ss/r4ss#814

**Comment by efletcherPIFSC** [comment]
@MOshima-PIFSC Need clarification for xlim and ylim values, stated in issue #67.
