### ISSUE TITLE
Update CITATION ?

### ISSUE THREAD

**Issue by efletcherPIFSC** [nmfs-ost/ss3diags#25]
Should there be any additions or updates to ss3diags references? The original citation references the article _A Cookbook for using model diagnostics in integrated stock assessments_ (Carvalho et. al., 2021)  

```
citHeader("To cite ss3diags in publications use:")

citEntry(
  entry    = "Article",
  title    = "A cookbook for using model diagnostics in integrated stock assessments",
  author   = personList(as.person("Felipe Carvalho"), as.person("Henning Winker"), as.person("Dean Courtney"), as.person("Maia Kapur"), as.person( "Laurence Kell"), as.person("Massimiliano Cardinale"), as.person("Michael Schirripa"), as.person("Toshihide Kitakado"), as.person("Dawit Yemane"), as.person("Kevin R. Piner"), as.person("Mark N. Maunder"), as.person("Ian Taylor"), as.person("Chantel R. Wetzel"), as.person("Kathryn Doering"), as.person("Kelli F. Johnson"), as.person("Richard D. Methot")),
  journal  = "Fisheries Research",
  year     = "2021",
  volume   = "240",
  pages    = "105959",
  url      = "https://www.sciencedirect.com/science/article/pii/S0165783621000874",
  issn    = "0165-7836",
  doi     = "https://doi.org/10.1016/j.fishres.2021.105959",
  textVersion = 
  paste(  "Carvalho, F., Winker, H., Courtney, D., Kapur, M., Kell, L., Cardinale, M., ", 
          "Schirripag, M., Kitakado, T., Yemane, D., Piner, K.R., Maunder, M.N., ",
          "Taylor, I., Wetzel, C.R., Doering, K., Johnsonm, K.F., Methot, R.D.",
          "2021. A cookbook for using model diagnostics in integrated stock assessments.",
          "Fisheries Research. 240, 1-18. https://doi.org/10.1016/j.fishres.2021.105959. "
  )
)

```

**Comment by MOshima-PIFSC** [comment]
I think we could change it to the actual R package since it has evolved from the original product.  We could change it to something like this:

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {ss3diags: Advanced diagnostics to evaluate a Stock Synthesis model},
    author = {Henning Winker, Felipe Carvalho, Massimiliano Cardinale, Laurence Kell, Megumi Oshima, and Eric Fletcher},
    year = {2022},
    note = {R package version 2.0.1},
    url = {https://github.com/PIFSCstockassessments/ss3diags},
  }

**Comment by efletcherPIFSC** [comment]
Commit c7921946851859590e7c166f9d80e8c58d39dc43,  package citation references DESCRIPTION file `citation ("ss3diags")`. Added date parameter in DESCRIPTION for citation references.

**Comment by MOshima-PIFSC** [comment]
Just realized we should update the readme with the new citation.

**Comment by efletcherPIFSC** [comment]
Re-rendering `README.rmd` rmarkdown document will update the `citation` content.

**Comment by efletcherPIFSC** [comment]
Deferring issue to #62
Re-rendering README.rmd will update the citation content.
