### ISSUE TITLE
ss3diags package description

### ISSUE THREAD

**Issue by efletcherPIFSC** [nmfs-ost/ss3diags#59]
What is the "MS" abbreviation used as in the *description* field?

https://github.com/PIFSCstockassessments/ss3diags/blob/f33675e9878430e69035f38813931746e5b1887b/DESCRIPTION#L31-L32

**Comment by MOshima-PIFSC** [comment]
@efletcherPIFSC I am not positive but I think MS is supposed to stand for manuscript? I think this could be changed to:
"Description: Compilation of diagnostic functions for Stock Synthesis models, which were developed for the manuscript "A Cookbook for Using Model Diagnostics in Integrated Stock Assessments".

**Comment by efletcherPIFSC** [comment]
@MOshima-PIFSC  Thanks you for the clarification and suggestion for this issue.
