### ISSUE TITLE
Add diags recipes to documentation site

### ISSUE THREAD

**Issue by MOshima-PIFSC** [nmfs-ost/ss3diags#75]
Convert the recipe scripts to qmds and host on documentation site.

**Comment by efletcherPIFSC** [comment]
@MOshima-PIFSC 
Will the recipe scripts be in own vignette file, or in the README? Do they require the example data sets?

**Comment by MOshima-PIFSC** [comment]
@efletcherPIFSC They would be in their own vignette files. I imagine adding them to the site under an articles tab. And they would  use the example data sets.

**Comment by MOshima-PIFSC** [comment]
Articles I want to include: 

- [x] Residual analyses (runs test and JABBA rmse plot)
- [x] Retrospective
- [x] Hindcast
- [x] Likelihood profile
- [x] Jitter 
- [x] ASPM
- [ ] delta MVLN
