### ISSUE TITLE
retrospective checks 

### ISSUE THREAD

**Issue by efletcherPIFSC** [nmfs-ost/ss3diags#89]
@MOshima-PIFSC 

When checking #88 codebase,
R package checker found errors with the test files, however this was because stock synthesis wasn't installed in my system,

```
> ## Run retrospectives
> r4ss::retro(dir = run_tmp, oldsubdir = "", newsubdir = "retrospectives", years = 0:-3, show_in_console = FALSE)
Error in check_exe(exe = exe, dir = olddir, verbose = verbose) : 
  ss.exe not found in C:\Users\ERIC~1.FLE\AppData\Local\Temp\Rtmpi0C64v/working_dir\RtmpMZOYd9/test-runs nor in the path.
Calls: <Anonymous> -> check_exe
Execution halted
```

 "run retrospectives" could be test_that module that could detect if the stock synthesis executable is on the system.

**Comment by MOshima-PIFSC** [comment]
@efletcherPIFSC I will fix this and add into the PR.

**Comment by MOshima-PIFSC** [comment]
@efletcherPIFSC I added some skip if statements to the tests. Please see if these work for you now.
Thanks!
