### ISSUE TITLE
build-ss-R-CMD-check: macOS-latest (release) error: "mv: rename ss_osx to ss: No such file or directory"

### ISSUE THREAD

**Issue by efletcherPIFSC** [nmfs-ost/ss3diags#90]
@MOshima-PIFSC 
"macOS-latest (release)" errors relate to filenname format issue: `ss_osx`

```
Run curl https://api.github.com/repos/nmfs-stock-synthesis/stock-synthesis/releases/latest | grep "browser_download_url" | grep -Eo 'https://[^\"]*' | grep "ss_osx" | xargs wget
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   277  100   277    0     0   3487      0 --:--:-- --:--:-- --:--:--  3644
mv: rename ss_osx to ss: No such file or directory
Error: Process completed with exit code 1.
```

The **macOS-latest workflow** from github action script:

https://github.com/PIFSCstockassessments/ss3diags/blob/d1d813c55e21a87a27a6e6c5884fed7aa5f5cb6c/.github/workflows/R-CMD-check.yaml#L48-L55

**Comment by MOshima-PIFSC** [comment]
@efletcherPIFSC this happens sometimes with the runs. I think its actually due to github not being able to connect and download the ss_osx file. I re-ran that [test](https://github.com/PIFSCstockassessments/ss3diags/actions/runs/5549638686/jobs/10200676010) (just the mac-os job) and it passed this time.

**Comment by MOshima-PIFSC** [comment]
I'm closing this issue, if this error occurs in the future you can either re-run the failed job manually, or wait to see if it passes the job the next time it is triggered.

**Comment by MOshima-PIFSC** [comment]
Re-opening this issue. I found a github action that will automatically re-try a step so I am going to try adding this into the workflow to see if it will help avoid this error.
